### ISSUE TITLE
base path in router

### ISSUE THREAD

**Issue by costafrancesco94** [rufusmaiwald/lumen-vue-app#8]
Hello :)
Don't know if theese instruction may be useful for someone, maybe it could be a good idea to put in the `readme.md`?

if for some reason someone has to pack the css/js/images files to a relative path instead of `/`, you can do the following:

1. add a `APP_BASE` variable to `.env` file, it defaults to `/` and can be replaced with `/something/path/with/ending/slash/`
3. add `publicPath: process.env.APP_BASE,` to `vue.config.json`
2. add `base: process.env.BASE_URL,` inside `@/js/vue/index.js`

I tested out with the apache method from #7 and it works. Can't really say WHY the var name chages from `vue.config.json` to router execution, probably `BASE_URL` is set by some vue magic and the APP_BASE is read from webpack automatically?

**Comment by costafrancesco94** [comment]
If you need to have same configuration files (or you are just lazy) between an apache server and dev host, put this file on project root and name it `builtin-router.php`, then start php builtin server with ` php -S localhost:8000 -t dist builtin-router.php`.
[builtin-router.zip](https://github.com/rufusmaiwald/lumen-vue-cli/files/5612843/builtin-router.zip)

**Comment by rufusmai** [comment]
Should now work in v2 with `npm run production` & `php artisan serve`.
